version: '3'
services:
  scrapper:
    build: ./docker/scrapper
    ports:
      - 5000:5000
    volumes:
      - ./docker/scrapper:/scrapper
    container_name: 'nubip-bot_scrapper'
    env_file:
      - ./docker/scrapper/.env

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: 'nubip-bot_elastic'
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  logstash:
    image: logstash:7.16.2
    container_name: 'nubip-bot_logstash'
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 9600:9600
      - 28777:28777
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.2
    container_name: 'nubip-bot_kibana'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
