version: '3'
services:
  scrapper:
    build:
      context: ./docker/scrapper
      args:
        NODE_ENV: development
    command: npm run dev

  bot:
    build:
      context: ./docker/bot
      args:
        NODE_ENV: development
    command: npm run dev
