version: '3'
services:
  scrapper:
    build:
      context: ./docker/scrapper
      args:
        NODE_ENV: production

  bot:
    build:
      context: ./docker/bot
      args:
        NODE_ENV: production
